### ISSUE TITLE
Question on Psarc lib usage

### ISSUE THREAD

**Issue by jcasement** [kokolihapihvi/Rocksmith2014PsarcLib#1]
@kokolihapihvi  -- Looking to use your Rocksmith PsarcLib.  Would you have a quick sample (Console C#) on how to use the Library.  I'm trying to capture and use AI against the songs attributes.  thx

**Comment by kokolihapihvi** [comment]
Hey!

I added a [readme](https://github.com/kokolihapihvi/Rocksmith2014PsarcLib/blob/main/README.md#example-usage) with some sample code, hope it helps!

**Comment by jcasement** [comment]
Excellent -- many thanks
